### ISSUE TITLE
Possibly add package main and export fns from there

### ISSUE THREAD

**Issue by brentvatne** [ajsmth/tailwind-react-native#1]
The [Snack](https://snack.expo.io) bundler does not play so well with private imports (eg: "tailwind-react-native/fns"), and it may also simplify the API to import directly from the `tailwind-react-native` package:

```
import { style, create, variant } from 'tailwind-react-native';
```

**Comment by ajsmth** [comment]
okay thanks! this was next on my list. 

funny you should say this as I had some not so fun bundling issues when trying to specify an index.js file, I suspect Expo was picking up on it. any ideas? 

I really like using expo as a quick way to test out changes on all three platforms while building the lib so I'd like to keep this workflow if possible

**Comment by ajsmth** [comment]
@brentvatne this is done on v0.2.5 - although I would like a better way of handling the expo embedded example project

**Comment by brentvatne** [comment]
@ajsmth - imo the nicest way is to use yarn workspaces, the hardest part is to just get it set up and after that it should be pretty easy to maintain. i set up yarn workspaces w/ this project on a branch here: https://github.com/brentvatne/tailwind-react-native/tree/%40brent/workspaces. with this structure, you would publish from the `lib` directory. the only thing to watch out for is to make sure that you have the same react-native/react/etc versions across the example app and the lib.

if you did end up breaking tailwind-react-native into some smaller packages (🤷 ) you could easily rename `lib` to `packages` and put the current `lib` contents inside of `packages/tailwind-react-native` (or you could just do that now if you wanted).

**Comment by ajsmth** [comment]
@brentvatne beautiful - thank you I'll switch over to this setup asap!

**Comment by ajsmth** [comment]
upgraded this yesterday - thanks so much for sharing it really is a much better workflow, i'll be using it in future projects for sure
