### ISSUE TITLE
Unable to run CLI

### ISSUE THREAD

**Issue by jonsamp** [ajsmth/tailwind-react-native#7]
I ran this:

```
➜ npx tailwind-react-native@latest init

sh: tailwind-react-native: command not found
```

Not sure why it says the `tailwind-react-native` command is not found. I tried installing `tailwind-react-native` with `volta`, and also with `npm`, but still got this message.

Here's what I get when installing with `volta`:

```
11:24:46 word-check-3 on main [!]
➜ volta install tailwind-react-native
success: installed tailwind-react-native@1.0.1 with executables: tailwind-react-native

11:25:31 word-check-3 on main [!]
➜ tailwind-react-native
Volta error: Could not locate executable `tailwind-react-native` in your project.

Please ensure that all project dependencies are installed with `npm install` or `yarn install`
```

I also tried running the **cli.js** file with commands like:

```bash
node ./node_modules/tailwind-react-native/build/cli.js
yarn run ./node_modules/tailwind-react-native/build/cli.js
```

Finally, I cloned this project and built it but have not been able to get it to run the CLI. Are other people able to run the CLI? If so, feel free to close this issue, since it could be something specific to my computer.

**Comment by ajsmth** [comment]
thanks @jonsamp :) should be updated w/ v 1.0.3! was missing some files in the distributed package
